# Functools: higher-order functions and operations on callable objects

from functools import reduce, partial, wraps, lru_cache, total_ordering
from functools import singledispatch, cached_property

print("=" * 5, "reduce: cumulative application", "=" * 5)

# Sum using reduce
numbers = [1, 2, 3, 4, 5]
total = reduce(lambda a, b: a + b, numbers)
print(f"Sum: {total}")  # 15

# Product using reduce
product = reduce(lambda a, b: a * b, numbers)
print(f"Product: {product}")  # 120

# Reduce with initial value
total_with_init = reduce(lambda a, b: a + b, numbers, 100)
print(f"Sum with initial 100: {total_with_init}")  # 115

# Find maximum using reduce
maximum = reduce(lambda a, b: a if a > b else b, numbers)
print(f"Max: {maximum}")  # 5

# Flatten a list of lists
lists = [[1, 2], [3, 4], [5, 6]]
flat = reduce(lambda a, b: a + b, lists)
print(f"Flatten: {flat}")  # [1, 2, 3, 4, 5, 6]

print("=" * 5, "partial: fixing function arguments", "=" * 5)

# Basic partial
def power(base, exponent):
    return base ** exponent

square = partial(power, exponent=2)
cube = partial(power, exponent=3)
print(f"Square of 5: {square(5)}")  # 25
print(f"Cube of 3: {cube(3)}")  # 27

# Partial with positional arguments
def greet(greeting, name):
    return f"{greeting}, {name}!"

hello = partial(greet, "Hello")
hi = partial(greet, "Hi")
print(hello("Alice"))  # Hello, Alice!
print(hi("Bob"))  # Hi, Bob!

# Partial with built-in functions
from decimal import Decimal, ROUND_HALF_UP

round2 = partial(round, ndigits=2)
print(f"Round to 2 places: {round2(3.14159)}")  # 3.14

# Practical: creating a logger with fixed prefix
import logging

logging.basicConfig(level=logging.INFO)

info_logger = partial(logging.info, "APP")
# info_logger("Started")  # logs: APP:Started

print("=" * 5, "lru_cache: memoization with least-recently-used eviction", "=" * 5)

# Basic lru_cache
@lru_cache(maxsize=128)
def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n - 1) + fibonacci(n - 2)

print(f"Fibonacci(50): {fibonacci(50)}")  # 12586269025 (instant!)

# Check cache info
print(f"Cache info: {fibonacci.cache_info()}")  # hits, misses, maxsize, currsize

# Clear cache
fibonacci.cache_clear()
print(f"After clear: {fibonacci.cache_info()}")

# Without cache: extremely slow for large n
# def fib_slow(n):
#     if n <= 1: return n
#     return fib_slow(n-1) + fib_slow(n-2)
# fib_slow(40) takes several seconds

# With cache: instant even for n=100+
@lru_cache(maxsize=None)  # unlimited cache
def factorial(n):
    if n <= 1:
        return 1
    return n * factorial(n - 1)

print(f"Factorial(20): {factorial(20)}")  # 2432902008176640000

# Cache expensive computation
@lru_cache(maxsize=32)
def expensive_computation(x, y):
    """Simulate an expensive computation."""
    import time
    time.sleep(0.01)  # simulate delay
    return x ** 2 + y ** 2

result1 = expensive_computation(3, 4)
result2 = expensive_computation(3, 4)  # cache hit
print(f"Result: {result1}, Cache hits: {expensive_computation.cache_info().hits}")

print("=" * 5, "@wraps: preserving function metadata", "=" * 5)

# Without @wraps: function metadata is lost
def bad_decorator(func):
    def wrapper(*args, **kwargs):
        return func(*args, **kwargs)
    return wrapper

@bad_decorator
def my_function():
    """This is my function."""
    pass

print(f"Name without wraps: {my_function.__name__}")  # wrapper
print(f"Doc without wraps: {my_function.__doc__}")  # None

# With @wraps: function metadata is preserved
def good_decorator(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        return func(*args, **kwargs)
    return wrapper

@good_decorator
def my_other_function():
    """This is my other function."""
    pass

print(f"Name with wraps: {my_other_function.__name__}")  # my_other_function
print(f"Doc with wraps: {my_other_function.__doc__}")  # This is my other function.

print("=" * 5, "total_ordering: generating comparison methods", "=" * 5)

@total_ordering
class Student:
    def __init__(self, name, grade):
        self.name = name
        self.grade = grade

    def __eq__(self, other):
        if not isinstance(other, Student):
            return NotImplemented
        return self.grade == other.grade

    def __lt__(self, other):
        if not isinstance(other, Student):
            return NotImplemented
        return self.grade < other.grade

    def __repr__(self):
        return f"Student('{self.name}', {self.grade})"

s1 = Student("Alice", 90)
s2 = Student("Bob", 85)
s3 = Student("Charlie", 90)

print(f"s1 > s2: {s1 > s2}")  # True (generated by @total_ordering)
print(f"s1 >= s3: {s1 >= s3}")  # True (generated)
print(f"s2 < s1: {s2 < s1}")  # True
print(f"s1 == s3: {s1 == s3}")  # True (same grade)

students = [Student("Diana", 95), Student("Eve", 80), Student("Frank", 88)]
print(f"Sorted: {sorted(students)}")
# [Student('Eve', 80), Student('Frank', 88), Student('Diana', 95)]

print("=" * 5, "singledispatch: generic functions by type", "=" * 5)

@singledispatch
def process(value):
    """Default handler for unknown types."""
    return f"Unknown type: {type(value).__name__}"

@process.register(int)
def _(value):
    return f"Integer: {value}, doubled: {value * 2}"

@process.register(str)
def _(value):
    return f"String: '{value}', length: {len(value)}"

@process.register(list)
def _(value):
    return f"List: {len(value)} items, sum: {sum(value) if all(isinstance(x, (int, float)) for x in value) else 'N/A'}"

@process.register(dict)
def _(value):
    return f"Dict: {len(value)} keys: {list(value.keys())}"

# Dispatch based on type
print(process(42))  # Integer: 42, doubled: 84
print(process("hello"))  # String: 'hello', length: 5
print(process([1, 2, 3]))  # List: 3 items, sum: 6
print(process({"a": 1, "b": 2}))  # Dict: 2 keys: ['a', 'b']
print(process(3.14))  # Unknown type: float

print("=" * 5, "cached_property: computed property with caching", "=" * 5)

class DataSet:
    def __init__(self, data):
        self._data = data

    @cached_property
    def mean(self):
        """Compute and cache the mean."""
        print("  Computing mean...")
        return sum(self._data) / len(self._data)

    @cached_property
    def variance(self):
        """Compute and cache the variance."""
        print("  Computing variance...")
        m = self.mean  # uses cached mean
        return sum((x - m) ** 2 for x in self._data) / len(self._data)

ds = DataSet([1, 2, 3, 4, 5])
print("First access to mean:")
print(f"Mean: {ds.mean}")  # Computing mean... → 3.0
print("Second access to mean:")
print(f"Mean: {ds.mean}")  # 3.0 (cached, no recomputation)
print(f"Variance: {ds.variance}")  # Computing variance... → 2.0 (uses cached mean)